name: Deploy

on: [push]
  branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PORT }}
          script: cd ${{ secrets.PROJECT_PATH }} && git pull && npm install && node app.js &
